apiVersion: v1
data:
  agent.yaml: |
    # Example environment overlay - customize for your environment
    # This file merges with base/agent.yaml

    # Override LLM configuration for this environment
    llm:
      openai:
        base_url: "http://litellm-service.litellm.svc.cluster.local:4000/v1/chat/completions"
        thinking_model: "claude-4-5-sonnet"
        summary_model: "claude-4-5-sonnet"

    # Override or add connections for this environment
    # For production, generate connections from https://app.synq.io/settings/scout
    #
    # This example shows minimal configuration - name, disabled, and parallelism
    # have sensible defaults and can be omitted
    connections:
      "52467b4f-cbab-4255-8cfc-07a11a726855":
        name: "PostgreSQL Example"
        parallelism: 2  # Override default of 8 for small dev database
        postgres:
          host: localhost
          port: 54320
          username: postgres
          password: ${POSTGRES_PASSWORD}
          database: db
          allow_insecure: true
kind: ConfigMap
metadata:
  name: example-synq-scout-agent-config
  namespace: synq
---
apiVersion: v1
data:
  BIGQUERY_SERVICE_ACCOUNT_KEY: eW91ci1iaWdxdWVyeS1zZXJ2aWNlLWFjY291bnQta2V5LWpzb24=
  CLICKHOUSE_PASSWORD: eW91ci1jbGlja2hvdXNlLXBhc3N3b3Jk
  DATABRICKS_ACCESS_TOKEN: eW91ci1kYXRhYnJpY2tzLWFjY2Vzcy10b2tlbg==
  MYSQL_PASSWORD: eW91ci1teXNxbC1wYXNzd29yZA==
  OPENAI_API_KEY: ZXhhbXBsZS1vcGVuYWktYXBpLWtleQ==
  POSTGRES_PASSWORD: cGFzcw==
  REDSHIFT_PASSWORD: eW91ci1yZWRzaGlmdC1wYXNzd29yZA==
  SNOWFLAKE_PRIVATE_KEY: eW91ci1zbm93Zmxha2UtcHJpdmF0ZS1rZXktcGVtLWNvbnRlbnQ=
  SYNQ_CLIENT_ID: ZXhhbXBsZS1jbGllbnQtaWQtZnJvbS1zeW5x
  SYNQ_CLIENT_SECRET: ZXhhbXBsZS1jbGllbnQtc2VjcmV0LWZyb20tc3lucQ==
  TRINO_PASSWORD: eW91ci10cmluby1wYXNzd29yZA==
kind: Secret
metadata:
  name: example-synq-scout-agent-env
  namespace: synq
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: minor
    keel.sh/pollSchedule: '@every 1m'
    keel.sh/trigger: poll
  name: example-synq-scout-deployment
  namespace: synq
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: synq-scout
  template:
    metadata:
      labels:
        deployment: synq-scout
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: example-synq-scout-agent-env
        image: europe-docker.pkg.dev/synq-cicd-public/synq-public/synq-scout:v0.1.10
        imagePullPolicy: Always
        name: synq-scout-container
        volumeMounts:
        - mountPath: /opt/synq-scout/
          name: synq-scout-agent-config-volume
      volumes:
      - configMap:
          name: example-synq-scout-agent-config
        name: synq-scout-agent-config-volume
